import json

STIX_PATH = "../feed/stix.json"
SIGMA_PATH = "../detections/sigma.yml"
YARA_PATH = "../detections/yara.yar"

def load_stix():
    with open(STIX_PATH, "r") as f:
        return json.load(f)

def extract_indicators(stix_obj):
    pattern = stix_obj["pattern"]
    parts = pattern.split(" OR ")

    indicators = []
    for p in parts:
        p = p.strip()

        if p.startswith("[ipv4-addr"):
            value = p.split("'")[1]
            indicators.append(("ipv4", value))

        elif p.startswith("[domain-name"):
            value = p.split("'")[1]
            indicators.append(("domain", value))

        elif p.startswith("[file:hashes"):
            value = p.split("'")[1]
            indicators.append(("sha256", value))

        elif p.startswith("[url"):
            value = p.split("'")[1]
            indicators.append(("url", value))

        elif p.startswith("[email-addr"):
            value = p.split("'")[1]
            indicators.append(("email", value))

    return indicators

def build_sigma(indicators):
    sigma = {
        "title": "Threat Intel Auto-Generated Rule",
        "id": "auto-generated-sigma-rule",
        "status": "experimental",
        "logsource": {"category": "network", "product": "windows"},
        "detection": {
            "selection": {},
            "condition": "selection"
        }
    }

    for ind_type, value in indicators:
        if ind_type == "ipv4":
            sigma["detection"]["selection"]["DestinationIp"] = value
        elif ind_type == "domain":
            sigma["detection"]["selection"]["QueryName"] = value
        elif ind_type == "url":
            sigma["detection"]["selection"]["Url"] = value
        elif ind_type == "email":
            sigma["detection"]["selection"]["SenderAddress"] = value
        elif ind_type == "sha256":
            sigma["detection"]["selection"]["FileHash"] = value

    return sigma

def build_yara(indicators):
    conditions = []

    for ind_type, value in indicators:
        if ind_type == "domain":
            conditions.append(f'for any i in (1..#domain): (domain[i] == "{value}")')
        elif ind_type == "ipv4":
            conditions.append(f'ip == "{value}"')
        elif ind_type == "sha256":
            conditions.append(f'hash.sha256 == "{value}"')
        elif ind_type == "url":
            conditions.append(f'url == "{value}"')
        elif ind_type == "email":
            conditions.append(f'email == "{value}"')

    yara_rule = f"""
rule ThreatIntelAutoGenerated
{{
    meta:
        description = "Auto-generated YARA rule from STIX indicators"

    strings:
        domain = "placeholder"

    condition:
        {" or ".join(conditions)}
}}
"""
    return yara_rule

def save_sigma(sigma_obj):
    with open(SIGMA_PATH, "w") as f:
        yaml_text = ""
        for key, value in sigma_obj.items():
            yaml_text += f"{key}: {value}\n"
        f.write(yaml_text)

def save_yara(yara_text):
    with open(YARA_PATH, "w") as f:
        f.write(yara_text)

def main():
    stix_obj = load_stix()
    indicators = extract_indicators(stix_obj)

    sigma = build_sigma(indicators)
    yara = build_yara(indicators)

    save_sigma(sigma)
    save_yara(yara)

    print("Sigma and YARA rules generated successfully.")

if __name__ == "__main__":
    main()
